apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: NodePort  # Change to NodePort for local access
  ports:
    - port: 80         # External port (standard HTTP port)
      targetPort: 3000  # Port where Next.js runs in the container
      nodePort: 30080   # Node port on which the service will be exposed
  selector:
    app: nextjs-app     # Ensure this matches your deployment's label selector
